<?php

namespace Database\Seeders;

use App\Models\Order;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class OrderSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $orders = [
            [
                'entry_date' => '2025-6-1',
                'exit_date' => '2025-6-23',
                'status' => 'Selesai',
                'order_package' => 'Reguler Cuci Setrika 3 hari',
                'type' => 'Kiloan',
                'price' => 7000,
                'weight' => 5.9,
                'total_price' => 41300,
                'customer_id' => 2,
            ],
            [
                'entry_date' => '2025-6-1',
                'exit_date' => '3035-6-6',
                'status' => 'Selesai',
                'order_package' => 'Reguler Cuci Setrika 3 hari',
                'type' => 'Kiloan',
                'price' => 7000,
                'weight' => 17.5,
                'total_price' => 122500,
                'customer_id' => 3,
            ],
            [
                'entry_date' => '2025-6-1',
                'exit_date' => '2025-6-5',
                'status' => 'Selesai',
                'order_package' => 'Reguler Cuci Setrika 3 hari',
                'type' => 'Kiloan',
                'price' => 7000,
                'weight' => 3.1,
                'total_price' => 21700,
                'customer_id' => 4,
            ],
            [
                'entry_date' => '2025-6-1',
                'exit_date' => '2025-9-6',
                'status' => 'Selesai',
                'order_package' => 'Reguler Cuci Setrika 3 hari',
                'type' => 'Kiloan',
                'price' => 7000,
                'weight' => 9,
                'total_price' => 63000,
                'customer_id' => 5,
            ],
            [
                'entry_date' => '2025-6-1',
                'exit_date' => '2025-9-6',
                'status' => 'Selesai',
                'order_package' => 'Reguler Cuci Lipat 3 hari',
                'type' => 'Kiloan',
                'price' => 6000,
                'weight' => 2.4,
                'total_price' => 14400,
                'customer_id' => 5,
            ],
            [
                'entry_date' => '2025-6-2',
                'exit_date' => '2025-6-10',
                'status' => 'Selesai',
                'order_package' => 'Reguler Cuci Setrika 3 hari',
                'type' => 'Kiloan',
                'price' => 7000,
                'weight' => 5.1,
                'total_price' => 35700,
                'customer_id' => 6,
            ],
            [
                'entry_date' => '2025-6-2',
                'exit_date' => '2025-6-10',
                'status' => 'Selesai',
                'order_package' => 'Reguler Cuci Lipat 3 hari',
                'type' => 'Kiloan',
                'price' => 6000,
                'weight' => 10.2,
                'total_price' => 61200,
                'customer_id' => 7,
            ],
            [
                'entry_date' => '2025-6-3',
                'exit_date' => '2025-6-9',
                'status' => 'Selesai',
                'order_package' => 'Reguler Cuci Setrika 3 hari',
                'type' => 'Kiloan',
                'price' => 7000,
                'weight' => 2.3,
                'total_price' => 16100,
                'customer_id' => 5,
            ],
            [
                'entry_date' => '2025-6-3',
                'exit_date' => '2025-6-6',
                'status' => 'Selesai',
                'order_package' => 'Reguler Setrika 3 hari',
                'type' => 'Kiloan',
                'price' => 5000,
                'weight' => 3.2,
                'total_price' => 16000,
                'customer_id' => 8,
            ],
            [
                'entry_date' => '2025-6-3',
                'exit_date' => '2025-6-9',
                'status' => 'Selesai',
                'order_package' => 'Reguler Cuci Setrika 3 hari',
                'type' => 'Kiloan',
                'price' => 7000,
                'weight' => 6.8,
                'total_price' => 47600,
                'customer_id' => 9,
            ],
            [
                'entry_date' => '2025-6-3',
                'exit_date' => '2025-6-8',
                'status' => 'Selesai',
                'order_package' => 'Reguler Cuci Setrika 3 hari',
                'type' => 'Kiloan',
                'price' => 7000,
                'weight' => 5.9,
                'total_price' => 41300,
                'customer_id' => 10,
            ],
            [
                'entry_date' => '2025-6-4',
                'exit_date' => '2025-6-19',
                'status' => 'Selesai',
                'order_package' => 'Reguler Cuci Lipat 3 hari',
                'type' => 'Kiloan',
                'price' => 6000,
                'weight' => 3.8,
                'total_price' => 22800,
                'customer_id' => 11,
            ],
            [
                'entry_date' => '2025-6-5',
                'exit_date' => '2025-6-10',
                'status' => 'Selesai',
                'order_package' => 'Bedcover Besar',
                'type' => 'Kiloan',
                'price' => 35000,
                'quantity' => 1,
                'total_price' => 35000,
                'customer_id' => 12,
            ],
            [
                'entry_date' => '2025-6-5',
                'exit_date' => '2025-6-10',
                'status' => 'Selesai',
                'order_package' => 'Reguler Cuci Setrika Lainnya',
                'type' => 'Kiloan',
                'price' => 10000,
                'weight' => 1.8,
                'total_price' => 18000,
                'customer_id' => 12,
            ],
            [
                'entry_date' => '2025-6-5',
                'exit_date' => '2025-6-10',
                'status' => 'Selesai',
                'order_package' => 'Reguler Cuci Setrika 3 hari',
                'type' => 'Kiloan',
                'price' => 7000,
                'weight' => 11.3,
                'total_price' => 79100,
                'customer_id' => 12,
            ],
            [
                'entry_date' => '2025-6-5',
                'exit_date' => '2025-6-8',
                'status' => 'Selesai',
                'order_package' => 'Reguler Cuci Setrika 3 hari',
                'type' => 'Kiloan',
                'price' => 7000,
                'weight' => 3.3,
                'total_price' => 23100,
                'customer_id' => 4,
            ],
            [
                'entry_date' => '2025-6-5',
                'exit_date' => '2025-6-8',
                'status' => 'Selesai',
                'order_package' => 'Reguler Cuci Setrika 3 hari',
                'type' => 'Kiloan',
                'price' => 7000,
                'weight' => 2.5,
                'total_price' => 17500,
                'customer_id' => 13,
            ],
            [
                'entry_date' => '2025-6-5',
                'exit_date' => '2025-6-6',
                'status' => 'Selesai',
                'order_package' => 'Reguler Cuci Setrika 3 hari',
                'type' => 'Kiloan',
                'price' => 7000,
                'weight' => 7,
                'total_price' => 49000,
                'customer_id' => 8,
            ],
            [
                'entry_date' => '2025-6-5',
                'exit_date' => '2025-6-9',
                'status' => 'Selesai',
                'order_package' => 'Reguler Cuci Setrika 3 hari',
                'type' => 'Kiloan',
                'price' => 7000,
                'weight' => 1.1,
                'total_price' => 7700,
                'customer_id' => 14,
            ],
            [
                'entry_date' => '2025-6-6',
                'exit_date' => '2025-6-9',
                'status' => 'Selesai',
                'order_package' => 'Reguler Cuci Setrika 3 hari',
                'type' => 'Kiloan',
                'price' => 7000,
                'weight' => 21.2,
                'total_price' => 148400,
                'customer_id' => 9,
            ],
            [
                'entry_date' => '2025-6-6',
                'exit_date' => '2025-6-10',
                'status' => 'Selesai',
                'order_package' => 'Reguler Cuci Setrika 3 hari',
                'type' => 'Kiloan',
                'price' => 7000,
                'weight' => 15.3,
                'total_price' => 107100,
                'customer_id' => 3,
            ],
            [
                'entry_date' => '2025-6-7',
                'exit_date' => '2025-6-10',
                'status' => 'Selesai',
                'order_package' => 'Reguler Cuci Setrika 3 hari',
                'type' => 'Kiloan',
                'price' => 7000,
                'weight' => 1.3,
                'total_price' => 9100,
                'customer_id' => 1,
            ],
            [
                'entry_date' => '2025-6-7',
                'exit_date' => '2025-6-9',
                'status' => 'Selesai',
                'order_package' => 'Reguler Cuci Setrika 3 hari',
                'type' => 'Kiloan',
                'price' => 7000,
                'weight' => 5,
                'total_price' => 35000,
                'customer_id' => 15,
            ],
            [
                'entry_date' => '2025-6-7',
                'exit_date' => '2025-6-10',
                'status' => 'Selesai',
                'order_package' => 'Reguler Cuci Setrika 3 hari',
                'type' => 'Kiloan',
                'price' => 7000,
                'weight' => 5.5,
                'total_price' => 38500,
                'customer_id' => 6,
            ],
            [
                'entry_date' => '2025-6-8',
                'exit_date' => '2025-6-12',
                'status' => 'Selesai',
                'order_package' => 'Reguler Cuci Setrika 3 hari',
                'type' => 'Kiloan',
                'price' => 7000,
                'weight' => 6.8,
                'total_price' => 47600,
                'customer_id' => 16,
            ],
            [
                'entry_date' => '2025-6-8',
                'exit_date' => '2025-6-13',
                'status' => 'Selesai',
                'order_package' => 'Reguler Cuci Setrika 3 hari',
                'type' => 'Kiloan',
                'price' => 7000,
                'weight' => 6.7,
                'total_price' => 46900,
                'customer_id' => 17,
            ],
            [
                'entry_date' => '2025-6-8',
                'exit_date' => '2025-6-12',
                'status' => 'Selesai',
                'order_package' => 'Reguler Cuci Setrika 3 hari',
                'type' => 'Kiloan',
                'price' => 7000,
                'weight' => 1.9,
                'total_price' => 13300,
                'customer_id' => 4,
            ],
            [
                'entry_date' => '2025-6-9',
                'exit_date' => '2025-6-29',
                'status' => 'Selesai',
                'order_package' => 'Bedcover Kecil',
                'type' => 'Lembaran',
                'price' => 25000,
                'quantity' => 2,
                'total_price' => 50000,
                'customer_id' => 18,
            ],
            [
                'entry_date' => '2025-6-9',
                'exit_date' => '2025-6-29',
                'status' => 'Selesai',
                'order_package' => 'Selimut',
                'type' => 'Lembaran',
                'price' => 10000,
                'quantity' => 2,
                'total_price' => 20000,
                'customer_id' => 18,
            ],
            [
                'entry_date' => '2025-6-9',
                'exit_date' => '2025-6-29',
                'status' => 'Selesai',
                'order_package' => 'Reguler Cuci Lipat Lainnya',
                'type' => 'Kiloan',
                'price' => 8000,
                'weight' => 1.9,
                'total_price' => 13300,
                'customer_id' => 18,
            ],
            [
                'entry_date' => '2025-6-9',
                'exit_date' => '2025-6-14',
                'status' => 'Selesai',
                'order_package' => 'Reguler Cuci Setrika 3 hari',
                'type' => 'Kiloan',
                'price' => 7000,
                'weight' => 15.2,
                'total_price' => 106400,
                'customer_id' => 9,
            ],
            [
                'entry_date' => '2025-6-9',
                'exit_date' => '2025-6-15',
                'status' => 'Selesai',
                'order_package' => 'Reguler Cuci Setrika 3 hari',
                'type' => 'Kiloan',
                'price' => 7000,
                'weight' => 3.7,
                'total_price' => 25900,
                'customer_id' => 5,
            ],
            [
                'entry_date' => '2025-6-9',
                'exit_date' => '2025-6-15',
                'status' => 'Selesai',
                'order_package' => 'Reguler Cuci Lipat 3 hari',
                'type' => 'Kiloan',
                'price' => 6000,
                'weight' => 6.6,
                'total_price' => 39600,
                'customer_id' => 5,
            ],
            [
                'entry_date' => '2025-6-9',
                'exit_date' => '2025-6-15',
                'status' => 'Selesai',
                'order_package' => 'Selimut',
                'type' => 'Lembaran',
                'price' => 10000,
                'quantity' => 1,
                'total_price' => 10000,
                'customer_id' => 5,
            ],
            [
                'entry_date' => '2025-6-9',
                'exit_date' => '2025-6-15',
                'status' => 'Selesai',
                'order_package' => 'Reguler Cuci Lipat Lainnya',
                'type' => 'Kiloan',
                'price' => 8000,
                'weight' => 1,
                'total_price' => 8000,
                'customer_id' => 5,
            ],
            [
                'entry_date' => '2025-6-10',
                'exit_date' => '2025-6-15',
                'status' => 'Selesai',
                'order_package' => 'Reguler Cuci Setrika 3 hari',
                'type' => 'Kiloan',
                'price' => 7000,
                'weight' => 7.4,
                'total_price' => 51800,
                'customer_id' => 12,
            ],
            [
                'entry_date' => '2025-6-10',
                'exit_date' => '2025-6-15',
                'status' => 'Selesai',
                'order_package' => 'Reguler Cuci Setrika Lainnya',
                'type' => 'Kiloan',
                'price' => 10000,
                'weight' => 2.8,
                'total_price' => 28000,
                'customer_id' => 12,
            ],
            [
                'entry_date' => '2025-6-10',
                'exit_date' => '2025-6-18',
                'status' => 'Selesai',
                'order_package' => 'Reguler Cuci Setrika 3 hari',
                'type' => 'Kiloan',
                'price' => 7000,
                'weight' => 10.1,
                'total_price' => 70700,
                'customer_id' => 3,
            ],
            [
                'entry_date' => '2025-6-11',
                'exit_date' => '2025-6-17',
                'status' => 'Selesai',
                'order_package' => 'Reguler Cuci Lipat 3 hari',
                'type' => 'Kiloan',
                'price' => 6000,
                'weight' => 9,
                'total_price' => 54000,
                'customer_id' => 7,
            ],
            [
                'entry_date' => '2025-6-12',
                'exit_date' => '2025-6-14',
                'status' => 'Selesai',
                'order_package' => 'Reguler Cuci Setrika 2 hari',
                'type' => 'Kiloan',
                'price' => 8000,
                'weight' => 4.8,
                'total_price' => 38400,
                'customer_id' => 15,
            ],
            [
                'entry_date' => '2025-6-12',
                'exit_date' => '2025-6-15',
                'status' => 'Selesai',
                'order_package' => 'Reguler Cuci Setrika 3 hari',
                'type' => 'Kiloan',
                'price' => 7000,
                'weight' => 4.4,
                'total_price' => 30800,
                'customer_id' => 4,
            ],
            [
                'entry_date' => '2025-6-13',
                'exit_date' => '2025-6-16',
                'status' => 'Selesai',
                'order_package' => 'Reguler Cuci Setrika 3 hari',
                'type' => 'Kiloan',
                'price' => 7000,
                'weight' => 6,
                'total_price' => 42000,
                'customer_id' => 17,
            ],
            [
                'entry_date' => '2025-6-13',
                'exit_date' => '2025-6-22',
                'status' => 'Selesai',
                'order_package' => 'Reguler Cuci Setrika 3 hari',
                'type' => 'Kiloan',
                'price' => 7000,
                'weight' => 1,
                'total_price' => 7000,
                'customer_id' => 13,
            ],
            [
                'entry_date' => '2025-6-13',
                'exit_date' => '2025-6-24',
                'status' => 'Selesai',
                'order_package' => 'Reguler Cuci Setrika 3 hari',
                'type' => 'Kiloan',
                'price' => 7000,
                'weight' => 6.5,
                'total_price' => 45500,
                'customer_id' => 6,
            ],
            [
                'entry_date' => '2025-6-13',
                'exit_date' => '2025-6-18',
                'status' => 'Selesai',
                'order_package' => 'Reguler Cuci Setrika 3 hari',
                'type' => 'Kiloan',
                'price' => 7000,
                'weight' => 5.1,
                'total_price' => 35700,
                'customer_id' => 8,
            ],
            [
                'entry_date' => '2025-6-13',
                'exit_date' => '2025-6-15',
                'status' => 'Selesai',
                'order_package' => 'Reguler Cuci Setrika 2 hari',
                'type' => 'Kiloan',
                'price' => 8000,
                'weight' => 1.4,
                'total_price' => 11200,
                'customer_id' => 14,
            ],
            [
                'entry_date' => '2025-6-14',
                'exit_date' => '2025-6-18',
                'status' => 'Selesai',
                'order_package' => 'Reguler Cuci Setrika 3 hari',
                'type' => 'Kiloan',
                'price' => 7000,
                'weight' => 16.3,
                'total_price' => 114100,
                'customer_id' => 9,
            ],
            [
                'entry_date' => '2025-6-14',
                'exit_date' => '2025-6-19',
                'status' => 'Selesai',
                'order_package' => 'Reguler Cuci Lipat 3 hari',
                'type' => 'Kiloan',
                'price' => 6000,
                'weight' => 5.1,
                'total_price' => 30600,
                'customer_id' => 11,
            ],
            [
                'entry_date' => '2025-6-14',
                'exit_date' => '2025-6-18',
                'status' => 'Selesai',
                'order_package' => 'Reguler Cuci Setrika 3 hari',
                'type' => 'Kiloan',
                'price' => 7000,
                'weight' => 14.4,
                'total_price' => 100800,
                'customer_id' => 3,
            ],
            [
                'entry_date' => '2025-6-14',
                'exit_date' => '2025-6-18',
                'status' => 'Selesai',
                'order_package' => 'Selimut',
                'type' => 'Lembaran',
                'price' => 10000,
                'quantity' => 1,
                'total_price' => 10000,
                'customer_id' => 3,
            ],
            [
                'entry_date' => '2025-6-14',
                'exit_date' => '2025-6-22',
                'status' => 'Selesai',
                'order_package' => 'Reguler Cuci Setrika 3 hari',
                'type' => 'Kiloan',
                'price' => 7000,
                'weight' => 1.4,
                'total_price' => 9800,
                'customer_id' => 15,
            ],
            [
                'entry_date' => '2025-6-15',
                'exit_date' => '2025-6-20',
                'status' => 'Selesai',
                'order_package' => 'Reguler Cuci Setrika Lainnya',
                'type' => 'Kiloan',
                'price' => 10000,
                'weight' => 3.1,
                'total_price' => 31000,
                'customer_id' => 12,
            ],
            [
                'entry_date' => '2025-6-15',
                'exit_date' => '2025-6-20',
                'status' => 'Selesai',
                'order_package' => 'Reguler Cuci Lipat Lainnya',
                'type' => 'Kiloan',
                'price' => 8000,
                'weight' => 11.9,
                'total_price' => 95200,
                'customer_id' => 12,
            ],
            [
                'entry_date' => '2025-6-15',
                'exit_date' => '2025-6-20',
                'status' => 'Selesai',
                'order_package' => 'Bedcover Kecil',
                'type' => 'Lembaran',
                'price' => 25000,
                'weight' => 1,
                'total_price' => 25000,
                'customer_id' => 12,
            ],
            [
                'entry_date' => '2025-6-15',
                'exit_date' => '2025-6-16',
                'status' => 'Selesai',
                'order_package' => 'Reguler Cuci Setrika 3 hari',
                'type' => 'Kiloan',
                'price' => 7000,
                'weight' => 1.4,
                'total_price' => 9800,
                'customer_id' => 1,
            ],
            [
                'entry_date' => '2025-6-15',
                'exit_date' => '2025-6-20',
                'status' => 'Selesai',
                'order_package' => 'Reguler Cuci Setrika 3 hari',
                'type' => 'Kiloan',
                'price' => 7000,
                'weight' => 1,
                'total_price' => 7000,
                'customer_id' => 5,
            ],
            [
                'entry_date' => '2025-6-15',
                'exit_date' => '2025-6-20',
                'status' => 'Selesai',
                'order_package' => 'Reguler Cuci Lipat 3 hari',
                'type' => 'Kiloan',
                'price' => 6000,
                'weight' => 2.4,
                'total_price' => 14400,
                'customer_id' => 5,
            ],
            [
                'entry_date' => '2025-6-15',
                'exit_date' => '2025-6-19',
                'status' => 'Selesai',
                'order_package' => 'Reguler Cuci Setrika 3 hari',
                'type' => 'Kiloan',
                'price' => 7000,
                'weight' => 3.4,
                'total_price' => 23800,
                'customer_id' => 4,
            ],
            [
                'entry_date' => '2025-6-16',
                'exit_date' => '2025-6-29',
                'status' => 'Selesai',
                'order_package' => 'Karpet Standar',
                'type' => 'Karpet',
                'price' => 10000,
                'length' => 160,
                'width' => 210,
                'total_price' => 33600,
                'customer_id' => 19,
            ],
            [
                'entry_date' => '2025-6-17',
                'exit_date' => '2025-7-2',
                'status' => 'Selesai',
                'order_package' => 'Reguler Cuci Lipat 3 hari',
                'type' => 'Kiloan',
                'price' => 6000,
                'weight' => 8.7,
                'total_price' => 52200,
                'customer_id' => 20,
            ],
            [
                'entry_date' => '2025-6-17',
                'exit_date' => '2025-7-2',
                'status' => 'Selesai',
                'order_package' => 'Selimut',
                'type' => 'Lembaran',
                'price' => 10000,
                'quantity' => 1,
                'total_price' => 10000,
                'customer_id' => 20,
            ],
            [
                'entry_date' => '2025-6-17',
                'exit_date' => '2025-7-2',
                'status' => 'Selesai',
                'order_package' => 'Bantal Besar',
                'type' => 'Satuan',
                'price' => 15000,
                'quantity' => 2,
                'total_price' => 30000,
                'customer_id' => 20,
            ],
            [
                'entry_date' => '2025-6-17',
                'exit_date' => '2025-7-2',
                'status' => 'Selesai',
                'order_package' => 'Kasur Lipat',
                'type' => 'Satuan',
                'price' => 25000,
                'quantity' => 1,
                'total_price' => 25000,
                'customer_id' => 20,
            ],
            [
                'entry_date' => '2025-6-18',
                'exit_date' => '2025-6-21',
                'status' => 'Selesai',
                'order_package' => 'Reguler Cuci Setrika 3 hari',
                'type' => 'Kiloan',
                'price' => 7000,
                'weight' => 11,
                'total_price' => 77000,
                'customer_id' => 9,
            ],
            [
                'entry_date' => '2025-6-18',
                'exit_date' => '2025-6-22',
                'status' => 'Selesai',
                'order_package' => 'Reguler Cuci Setrika 3 hari',
                'type' => 'Kiloan',
                'price' => 7000,
                'weight' => 15.3,
                'total_price' => 107800,
                'customer_id' => 3,
            ],
            [
                'entry_date' => '2025-6-18',
                'exit_date' => '2025-6-22',
                'status' => 'Selesai',
                'order_package' => 'Selimut',
                'type' => 'Lembaran',
                'price' => 10000,
                'quantity' => 1,
                'total_price' => 10000,
                'customer_id' => 3,
            ],
            [
                'entry_date' => '2025-6-18',
                'exit_date' => '2025-6-22',
                'status' => 'Selesai',
                'order_package' => 'Reguler Cuci Setrika 3 hari',
                'type' => 'Kiloan',
                'price' => 7000,
                'weight' => 2.2,
                'total_price' => 15400,
                'customer_id' => 4,
            ],
            [
                'entry_date' => '2025-6-20',
                'exit_date' => '2025-6-29',
                'status' => 'Selesai',
                'order_package' => 'Reguler Cuci Lipat 3 hari',
                'type' => 'Kiloan',
                'price' => 6000,
                'weight' => 1.2,
                'total_price' => 7200,
                'customer_id' => 21,
            ],
            [
                'entry_date' => '2025-6-20',
                'exit_date' => '2025-6-29',
                'status' => 'Selesai',
                'order_package' => 'Seprai',
                'type' => 'Lembaran',
                'price' => 10000,
                'quantity' => 1,
                'total_price' => 10000,
                'customer_id' => 21,
            ],
            [
                'entry_date' => '2025-6-20',
                'exit_date' => '2025-6-29',
                'status' => 'Selesai',
                'order_package' => 'Selimut',
                'type' => 'Lembaran',
                'price' => 10000,
                'quantity' => 1,
                'total_price' => 10000,
                'customer_id' => 21,
            ],
            [
                'entry_date' => '2025-6-20',
                'exit_date' => '2025-6-26',
                'status' => 'Selesai',
                'order_package' => 'Reguler Cuci Setrika 3 hari',
                'type' => 'Kiloan',
                'price' => 7000,
                'weight' => 9.9,
                'total_price' => 69300,
                'customer_id' => 12,
            ],
            [
                'entry_date' => '2025-6-20',
                'exit_date' => '2025-6-26',
                'status' => 'Selesai',
                'order_package' => 'Reguler Cuci Setrika Lainnya',
                'type' => 'Kiloan',
                'price' => 10000,
                'weight' => 2.1,
                'total_price' => 21000,
                'customer_id' => 12,
            ],
            [
                'entry_date' => '2025-6-20',
                'exit_date' => '2025-6-23',
                'status' => 'Selesai',
                'order_package' => 'Reguler Cuci Setrika 3 hari',
                'type' => 'Kiloan',
                'price' => 7000,
                'weight' => 1.8,
                'total_price' => 12600,
                'customer_id' => 1,
            ],
            [
                'entry_date' => '2025-6-20',
                'exit_date' => '2025-6-24',
                'status' => 'Selesai',
                'order_package' => 'Reguler Cuci Setrika 3 hari',
                'type' => 'Kiloan',
                'price' => 7000,
                'weight' => 6.5,
                'total_price' => 45500,
                'customer_id' => 6,
            ],
            [
                'entry_date' => '2025-6-20',
                'exit_date' => '2025-6-22',
                'status' => 'Selesai',
                'order_package' => 'Reguler Cuci Setrika 2 hari',
                'type' => 'Kiloan',
                'price' => 8000,
                'weight' => 1.5,
                'total_price' => 12000,
                'customer_id' => 14,
            ],
            [
                'entry_date' => '2025-6-20',
                'exit_date' => '2025-7-4',
                'status' => 'Selesai',
                'order_package' => 'Reguler Cuci Lipat 3 hari',
                'type' => 'Kiloan',
                'price' => 6000,
                'weight' => 7.2,
                'total_price' => 43200,
                'customer_id' => 7,
            ],
            [
                'entry_date' => '2025-6-20',
                'exit_date' => '2025-7-4',
                'status' => 'Selesai',
                'order_package' => 'Bedcover Sedang',
                'type' => 'Lembaran',
                'price' => 30000,
                'quantity' => 1,
                'total_price' => 30000,
                'customer_id' => 7,
            ],
            [
                'entry_date' => '2025-6-20',
                'exit_date' => '2025-6-23',
                'status' => 'Selesai',
                'order_package' => 'Reguler Cuci Setrika 3 hari',
                'type' => 'Kiloan',
                'price' => 7000,
                'weight' => 1.6,
                'total_price' => 11200,
                'customer_id' => 5,
            ],
            [
                'entry_date' => '2025-6-20',
                'exit_date' => '2025-6-23',
                'status' => 'Selesai',
                'order_package' => 'Reguler Cuci Lipat 3 hari',
                'type' => 'Kiloan',
                'price' => 6000,
                'weight' => 2.6,
                'total_price' => 15600,
                'customer_id' => 5,
            ],
            [
                'entry_date' => '2025-6-20',
                'exit_date' => '2025-6-22',
                'status' => 'Selesai',
                'order_package' => 'Reguler Cuci Setrika 3 hari',
                'type' => 'Kiloan',
                'price' => 7000,
                'weight' => 3.6,
                'total_price' => 25200,
                'customer_id' => 15,
            ],
            [
                'entry_date' => '2025-6-20',
                'exit_date' => '2025-6-24',
                'status' => 'Selesai',
                'order_package' => 'Bedcover Kecil',
                'type' => 'Lembaran',
                'price' => 25000,
                'quantity' => 1,
                'total_price' => 25000,
                'customer_id' => 17,
            ],
            [
                'entry_date' => '2025-6-21',
                'exit_date' => '2025-6-23',
                'status' => 'Selesai',
                'order_package' => 'Reguler Cuci Setrika 2 hari',
                'type' => 'Kiloan',
                'price' => 8000,
                'weight' => 3.7,
                'total_price' => 29600,
                'customer_id' => 22,
            ],
            [
                'entry_date' => '2025-6-21',
                'exit_date' => '2025-6-23',
                'status' => 'Selesai',
                'order_package' => 'Selimut',
                'type' => 'Lembaran',
                'price' => 10000,
                'quantity' => 1,
                'total_price' => 10000,
                'customer_id' => 22,
            ],
            [
                'entry_date' => '2025-6-21',
                'exit_date' => '2025-6-24',
                'status' => 'Selesai',
                'order_package' => 'Reguler Cuci Setrika 3 hari',
                'type' => 'Kiloan',
                'price' => 7000,
                'weight' => 9.5,
                'total_price' => 66500,
                'customer_id' => 9,
            ],
            [
                'entry_date' => '2025-6-21',
                'exit_date' => '2025-6-30',
                'status' => 'Selesai',
                'order_package' => 'Ambal',
                'type' => 'Lembaran',
                'price' => 30000,
                'quantity' => 1,
                'total_price' => 30000,
                'customer_id' => 23,
            ],
            [
                'entry_date' => '2025-6-22',
                'exit_date' => '2025-6-29',
                'status' => 'Selesai',
                'order_package' => 'Reguler Cuci Setrika 3 hari',
                'type' => 'Kiloan',
                'price' => 7000,
                'weight' => 3.2,
                'total_price' => 22400,
                'customer_id' => 15,
            ],
            [
                'entry_date' => '2025-6-22',
                'exit_date' => '2025-6-26',
                'status' => 'Selesai',
                'order_package' => 'Reguler Cuci Setrika 3 hari',
                'type' => 'Kiloan',
                'price' => 7000,
                'weight' => 1.8,
                'total_price' => 12600,
                'customer_id' => 4,
            ],
            [
                'entry_date' => '2025-6-22',
                'exit_date' => '2025-6-26',
                'status' => 'Selesai',
                'order_package' => 'Reguler Cuci Setrika 3 hari',
                'type' => 'Kiloan',
                'price' => 7000,
                'weight' => 12.6,
                'total_price' => 88200,
                'customer_id' => 3,
            ],
            [
                'entry_date' => '2025-6-22',
                'exit_date' => '2025-6-26',
                'status' => 'Selesai',
                'order_package' => 'Seprai',
                'type' => 'Lembaran',
                'price' => 10000,
                'quantity' => 1,
                'total_price' => 10000,
                'customer_id' => 3,
            ],
            [
                'entry_date' => '2025-6-23',
                'exit_date' => '2025-6-26',
                'status' => 'Selesai',
                'order_package' => 'Reguler Cuci Lipat 3 hari',
                'type' => 'Kiloan',
                'price' => 6000,
                'weight' => 7.2,
                'total_price' => 43200,
                'customer_id' => 5,
            ],
            [
                'entry_date' => '2025-6-23',
                'exit_date' => '2025-6-26',
                'status' => 'Selesai',
                'order_package' => 'Reguler Cuci Setrika 3 hari',
                'type' => 'Kiloan',
                'price' => 7000,
                'weight' => 6.6,
                'total_price' => 46200,
                'customer_id' => 5,
            ],
            [
                'entry_date' => '2025-6-23',
                'exit_date' => '2025-6-26',
                'status' => 'Selesai',
                'order_package' => 'Selimut',
                'type' => 'Lembaran',
                'price' => 10000,
                'quantity' => 1,
                'total_price' => 10000,
                'customer_id' => 5,
            ],
            [
                'entry_date' => '2025-6-23',
                'exit_date' => '2025-7-1',
                'status' => 'Selesai',
                'order_package' => 'Reguler Cuci Lipat 3 hari',
                'type' => 'Kiloan',
                'price' => 6000,
                'weight' => 5.5,
                'total_price' => 33000,
                'customer_id' => 10,
            ],
            [
                'entry_date' => '2025-6-24',
                'exit_date' => '2025-6-29',
                'status' => 'Selesai',
                'order_package' => 'Ambal',
                'type' => 'Lembaran',
                'price' => 30000,
                'quantity' => 1,
                'total_price' => 30000,
                'customer_id' => 17,
            ],
            [
                'entry_date' => '2025-6-24',
                'exit_date' => '2025-6-26',
                'status' => 'Selesai',
                'order_package' => 'Reguler Cuci Setrika 3 hari',
                'type' => 'Kiloan',
                'price' => 7000,
                'weight' => 5.9,
                'total_price' => 41300,
                'customer_id' => 2,
            ],
            [
                'entry_date' => '2025-6-24',
                'exit_date' => '2025-6-26',
                'status' => 'Selesai',
                'order_package' => 'Seprai',
                'type' => 'Lembaran',
                'price' => 10000,
                'quantity' => 1,
                'total_price' => 10000,
                'customer_id' => 2,
            ],
            [
                'entry_date' => '2025-6-24',
                'exit_date' => '2025-6-26',
                'status' => 'Selesai',
                'order_package' => 'Reguler Cuci Lipat Lainnya',
                'type' => 'Kiloan',
                'price' => 8000,
                'weight' => 1,
                'total_price' => 8000,
                'customer_id' => 2,
            ],
            [
                'entry_date' => '2025-6-25',
                'exit_date' => null,
                'status' => 'Selesai Diproses',
                'order_package' => 'Reguler Cuci Lipat 3 hari',
                'type' => 'Kiloan',
                'price' => 6000,
                'weight' => 11.1,
                'total_price' => 66600,
                'customer_id' => 24,
            ],
            [
                'entry_date' => '2025-6-25',
                'exit_date' => null,
                'status' => 'Selesai Diproses',
                'order_package' => 'Selimut',
                'type' => 'Lembaran',
                'price' => 10000,
                'quantity' => 1,
                'total_price' => 10000,
                'customer_id' => 24,
            ],
            [
                'entry_date' => '2025-6-25',
                'exit_date' => null,
                'status' => 'Selesai Diproses',
                'order_package' => 'Bantal Standar',
                'type' => 'Satuan',
                'price' => 10000,
                'quantity' => 1,
                'total_price' => 10000,
                'customer_id' => 24,
            ],
            [
                'entry_date' => '2025-6-26',
                'exit_date' => '2025-7-5',
                'status' => 'Selesai',
                'order_package' => 'Seprai',
                'type' => 'Lembaran',
                'price' => 10000,
                'quantity' => 1,
                'total_price' => 10000,
                'customer_id' => 5,
            ],
            [
                'entry_date' => '2025-6-26',
                'exit_date' => '2025-7-5',
                'status' => 'Selesai',
                'order_package' => 'Selimut',
                'type' => 'Lembaran',
                'price' => 10000,
                'quantity' => 1,
                'total_price' => 10000,
                'customer_id' => 5,
            ],
            [
                'entry_date' => '2025-6-26',
                'exit_date' => '2025-7-1',
                'status' => 'Selesai',
                'order_package' => 'Reguler Cuci Setrika 3 hari',
                'type' => 'Kiloan',
                'price' => 7000,
                'weight' => 9.4,
                'total_price' => 65800,
                'customer_id' => 12,
            ],
            [
                'entry_date' => '2025-6-26',
                'exit_date' => '2025-7-1',
                'status' => 'Selesai',
                'order_package' => 'Reguler Cuci Setrika Lainnya',
                'type' => 'Kiloan',
                'price' => 10000,
                'weight' => 1.9,
                'total_price' => 19000,
                'customer_id' => 12,
            ],
            [
                'entry_date' => '2025-6-26',
                'exit_date' => '2025-6-29',
                'status' => 'Selesai',
                'order_package' => 'Reguler Cuci Setrika 3 hari',
                'type' => 'Kiloan',
                'price' => 7000,
                'weight' => 4.8,
                'total_price' => 33600,
                'customer_id' => 2,
            ],
            [
                'entry_date' => '2025-6-26',
                'exit_date' => '2025-7-1',
                'status' => 'Selesai',
                'order_package' => 'Reguler Cuci Setrika 3 hari',
                'type' => 'Kiloan',
                'price' => 7000,
                'weight' => 12.3,
                'total_price' => 86100,
                'customer_id' => 3,
            ],
            [
                'entry_date' => '2025-6-26',
                'exit_date' => '2025-6-29',
                'status' => 'Selesai',
                'order_package' => 'Reguler Cuci Setrika 3 hari',
                'type' => 'Kiloan',
                'price' => 7000,
                'weight' => 2.8,
                'total_price' => 19600,
                'customer_id' => 4,
            ],
            [
                'entry_date' => '2025-6-27',
                'exit_date' => '2025-6-29',
                'status' => 'Selesai',
                'order_package' => 'Reguler Cuci Setrika 3 hari',
                'type' => 'Kiloan',
                'price' => 7000,
                'weight' => 14.7,
                'total_price' => 102900,
                'customer_id' => 9,
            ],
            [
                'entry_date' => '2025-6-27',
                'exit_date' => '2025-6-29',
                'status' => 'Selesai',
                'order_package' => 'Selimut',
                'type' => 'Lembaran',
                'price' => 10000,
                'quantity' => 1,
                'total_price' => 10000,
                'customer_id' => 9,
            ],
            [
                'entry_date' => '2025-6-27',
                'exit_date' => '2025-6-29',
                'status' => 'Selesai',
                'order_package' => 'Reguler Cuci Setrika 3 hari',
                'type' => 'Kiloan',
                'price' => 7000,
                'weight' => 7,
                'total_price' => 49000,
                'customer_id' => 17,
            ],
            [
                'entry_date' => '2025-6-27',
                'exit_date' => '2025-6-29',
                'status' => 'Selesai',
                'order_package' => 'Selimut',
                'type' => 'Lembaran',
                'price' => 10000,
                'quantity' => 1,
                'total_price' => 10000,
                'customer_id' => 17,
            ],
            [
                'entry_date' => '2025-6-27',
                'exit_date' => '2025-7-8',
                'status' => 'Selesai',
                'order_package' => 'Reguler Cuci Setrika 3 hari',
                'type' => 'Kiloan',
                'price' => 7000,
                'weight' => 8.8,
                'total_price' => 61600,
                'customer_id' => 6,
            ],
            [
                'entry_date' => '2025-6-27',
                'exit_date' => '2025-7-1',
                'status' => 'Selesai',
                'order_package' => 'Reguler Cuci Lipat Lainnya',
                'type' => 'Kiloan',
                'price' => 8000,
                'weight' => 3.6,
                'total_price' => 28800,
                'customer_id' => 10,
            ],
            [
                'entry_date' => '2025-6-28',
                'exit_date' => '2025-7-4',
                'status' => 'Selesai',
                'order_package' => 'Reguler Cuci Setrika 2 hari',
                'type' => 'Kiloan',
                'price' => 7000,
                'weight' => 1.2,
                'total_price' => 9600,
                'customer_id' => 14,
            ],
            [
                'entry_date' => '2025-6-28',
                'exit_date' => '2025-7-4',
                'status' => 'Selesai',
                'order_package' => 'Reguler Cuci Setrika 3 hari',
                'type' => 'Kiloan',
                'price' => 7000,
                'weight' => 10.6,
                'total_price' => 74200,
                'customer_id' => 25,
            ],
            [
                'entry_date' => '2025-6-28',
                'exit_date' => '2025-6-29',
                'status' => 'Selesai',
                'order_package' => 'Reguler Cuci Setrika 3 hari',
                'type' => 'Kiloan',
                'price' => 7000,
                'weight' => 4,
                'total_price' => 28000,
                'customer_id' => 15,
            ],
            [
                'entry_date' => '2025-6-29',
                'exit_date' => '2025-7-2',
                'status' => 'Selesai',
                'order_package' => 'Reguler Cuci Setrika 3 hari',
                'type' => 'Kiloan',
                'price' => 7000,
                'weight' => 8.9,
                'total_price' => 62300,
                'customer_id' => 2,
            ],
            [
                'entry_date' => '2025-6-29',
                'exit_date' => '2025-7-13',
                'status' => 'Selesai',
                'order_package' => 'Reguler Cuci Setrika 3 hari',
                'type' => 'Kiloan',
                'price' => 7000,
                'weight' => 1.6,
                'total_price' => 11200,
                'customer_id' => 15,
            ],
            [
                'entry_date' => '2025-6-29',
                'exit_date' => '2025-7-3',
                'status' => 'Selesai',
                'order_package' => 'Reguler Cuci Setrika 3 hari',
                'type' => 'Kiloan',
                'price' => 7000,
                'weight' => 2.3,
                'total_price' => 16100,
                'customer_id' => 4,
            ],
            [
                'entry_date' => '2025-6-29',
                'exit_date' => '2025-6-30',
                'status' => 'Selesai',
                'order_package' => 'Reguler Cuci Setrika 3 hari',
                'type' => 'Kiloan',
                'price' => 8000,
                'weight' => 6,
                'total_price' => 50000,
                'customer_id' => 17,
            ],
            [
                'entry_date' => '2025-7-1',
                'exit_date' => '2025-7-4',
                'status' => 'Selesai',
                'order_package' => 'Reguler Cuci Setrika 3 hari',
                'type' => 'Kiloan',
                'price' => 7000,
                'weight' => 16,
                'total_price' => 112000,
                'customer_id' => 9,
            ],
            [
                'entry_date' => '2025-7-1',
                'exit_date' => '2025-7-4',
                'status' => 'Selesai',
                'order_package' => 'Selimut',
                'type' => 'Lembaran',
                'price' => 10000,
                'quantity' => 1,
                'total_price' => 10000,
                'customer_id' => 9,
            ],
            [
                'entry_date' => '2025-7-1',
                'exit_date' => '2025-7-5',
                'status' => 'Selesai',
                'order_package' => 'Reguler Cuci Setrika 3 hari',
                'type' => 'Kiloan',
                'price' => 7000,
                'weight' => 6.5,
                'total_price' => 45500,
                'customer_id' => 12,
            ],
            [
                'entry_date' => '2025-7-1',
                'exit_date' => '2025-7-5',
                'status' => 'Selesai',
                'order_package' => 'Bedcover Kecil',
                'type' => 'Lembaran',
                'price' => 25000,
                'quantity' => 2,
                'total_price' => 50000,
                'customer_id' => 12,
            ],
            [
                'entry_date' => '2025-7-1',
                'exit_date' => '2025-7-5',
                'status' => 'Selesai',
                'order_package' => 'Reguler Cuci Setrika Lainnya',
                'type' => 'Kiloan',
                'price' => 10000,
                'weight' => 3,
                'total_price' => 30000,
                'customer_id' => 12,
            ],
            [
                'entry_date' => '2025-7-1',
                'exit_date' => '2025-7-5',
                'status' => 'Selesai',
                'order_package' => 'Reguler Cuci Setrika 3 hari',
                'type' => 'Kiloan',
                'price' => 7000,
                'weight' => 2.3,
                'total_price' => 16100,
                'customer_id' => 26,
            ],
            [
                'entry_date' => '2025-7-1',
                'exit_date' => '2025-7-5',
                'status' => 'Selesai',
                'order_package' => 'Seprai',
                'type' => 'Lembaran',
                'price' => 10000,
                'quantity' => 1,
                'total_price' => 10000,
                'customer_id' => 26,
            ],
            [
                'entry_date' => '2025-7-1',
                'exit_date' => '2025-7-6',
                'status' => 'Selesai',
                'order_package' => 'Reguler Cuci Setrika 3 hari',
                'type' => 'Kiloan',
                'price' => 7000,
                'weight' => 15.8,
                'total_price' => 110600,
                'customer_id' => 3,
            ],
            [
                'entry_date' => '2025-7-1',
                'exit_date' => '2025-7-8',
                'status' => 'Selesai',
                'order_package' => 'Reguler Cuci Lipat 3 hari',
                'type' => 'Kiloan',
                'price' => 6000,
                'weight' => 5,
                'total_price' => 30000,
                'customer_id' => 11,
            ],
            [
                'entry_date' => '2025-7-1',
                'exit_date' => '2025-7-8',
                'status' => 'Selesai',
                'order_package' => 'Seprai',
                'type' => 'Lembaran',
                'price' => 10000,
                'quantity' => 2,
                'total_price' => 20000,
                'customer_id' => 11,
            ],
            [
                'entry_date' => '2025-7-1',
                'exit_date' => null,
                'status' => 'Selesai Diproses',
                'order_package' => 'Reguler Cuci Lipat 3 hari',
                'type' => 'Kiloan',
                'price' => 6000,
                'weight' => 1.8,
                'total_price' => 10800,
                'customer_id' => 10,
            ],
            [
                'entry_date' => '2025-7-2',
                'exit_date' => '2025-7-7',
                'status' => 'Selesai',
                'order_package' => 'Reguler Cuci Lipat 3 hari',
                'type' => 'Kiloan',
                'price' => 6000,
                'weight' => 2.4,
                'total_price' => 14400,
                'customer_id' => 5,
            ],
            [
                'entry_date' => '2025-7-2',
                'exit_date' => '2025-7-7',
                'status' => 'Selesai',
                'order_package' => 'Reguler Cuci Setrika 3 hari',
                'type' => 'Kiloan',
                'price' => 7000,
                'weight' => 1.9,
                'total_price' => 13300,
                'customer_id' => 5,
            ],
            [
                'entry_date' => '2025-7-3',
                'exit_date' => '2025-7-8',
                'status' => 'Selesai',
                'order_package' => 'Reguler Cuci Lipat 3 hari',
                'type' => 'Kiloan',
                'price' => 6000,
                'weight' => 7.4,
                'total_price' => 44400,
                'customer_id' => 11,
            ],
            [
                'entry_date' => '2025-7-3',
                'exit_date' => '2025-7-5',
                'status' => 'Selesai',
                'order_package' => 'Reguler Cuci Setrika 3 hari',
                'type' => 'Kiloan',
                'price' => 7000,
                'weight' => 1.6,
                'total_price' => 11200,
                'customer_id' => 4,
            ],
            [
                'entry_date' => '2025-7-4',
                'exit_date' => '2025-7-9',
                'status' => 'Selesai',
                'order_package' => 'Reguler Cuci Setrika 3 hari',
                'type' => 'Kiloan',
                'price' => 7000,
                'weight' => 7.7,
                'total_price' => 53900,
                'customer_id' => 9,
            ],
            [
                'entry_date' => '2025-7-4',
                'exit_date' => '2025-7-7',
                'status' => 'Selesai',
                'order_package' => 'Reguler Cuci Setrika 3 hari',
                'type' => 'Kiloan',
                'price' => 7000,
                'weight' => 8,
                'total_price' => 56000,
                'customer_id' => 2,
            ],
            [
                'entry_date' => '2025-7-4',
                'exit_date' => '2025-7-12',
                'status' => 'Selesai',
                'order_package' => 'Reguler Cuci Lipat 3 hari',
                'type' => 'Kiloan',
                'price' => 6000,
                'weight' => 16.9,
                'total_price' => 101400,
                'customer_id' => 7,
            ],
            [
                'entry_date' => '2025-7-5',
                'exit_date' => '2025-7-8',
                'status' => 'Selesai',
                'order_package' => 'Reguler Cuci Setrika 3 hari',
                'type' => 'Kiloan',
                'price' => 7000,
                'weight' => 2.4,
                'total_price' => 16800,
                'customer_id' => 21,
            ],
            [
                'entry_date' => '2025-7-5',
                'exit_date' => '2025-7-8',
                'status' => 'Selesai',
                'order_package' => 'Selimut',
                'type' => 'Lembaran',
                'price' => 10000,
                'quantity' => 1,
                'total_price' => 10000,
                'customer_id' => 21,
            ],
            [
                'entry_date' => '2025-7-5',
                'exit_date' => '2025-7-9',
                'status' => 'Selesai',
                'order_package' => 'Reguler Cuci Setrika 3 hari',
                'type' => 'Kiloan',
                'price' => 7000,
                'weight' => 6.5,
                'total_price' => 45500,
                'customer_id' => 12,
            ],
            [
                'entry_date' => '2025-7-5',
                'exit_date' => '2025-7-9',
                'status' => 'Selesai',
                'order_package' => 'Reguler Cuci Setrika Lainnya',
                'type' => 'Kiloan',
                'price' => 10000,
                'weight' => 1.3,
                'total_price' => 13000,
                'customer_id' => 12,
            ],
            [
                'entry_date' => '2025-7-5',
                'exit_date' => '2025-7-10',
                'status' => 'Selesai',
                'order_package' => 'Reguler Cuci Setrika 3 hari',
                'type' => 'Kiloan',
                'price' => 7000,
                'weight' => 3,
                'total_price' => 21000,
                'customer_id' => 4,
            ],
            [
                'entry_date' => '2025-7-6',
                'exit_date' => '2025-7-8',
                'status' => 'Selesai',
                'order_package' => 'Reguler Cuci Setrika 3 hari',
                'type' => 'Kiloan',
                'price' => 7000,
                'weight' => 12,
                'total_price' => 84000,
                'customer_id' => 6,
            ],
            [
                'entry_date' => '2025-7-6',
                'exit_date' => '2025-7-8',
                'status' => 'Selesai',
                'order_package' => 'Seprai',
                'type' => 'Lembaran',
                'price' => 10000,
                'quantity' => 1,
                'total_price' => 10000,
                'customer_id' => 6,
            ],
            [
                'entry_date' => '2025-7-6',
                'exit_date' => null,
                'status' => 'Selesai Diproses',
                'order_package' => 'Reguler Cuci Setrika 3 hari',
                'type' => 'Kiloan',
                'price' => 7000,
                'weight' => 17.8,
                'total_price' => 124600,
                'customer_id' => 3,
            ],
            [
                'entry_date' => '2025-7-6',
                'exit_date' => '2025-7-13',
                'status' => 'Selesai',
                'order_package' => 'Reguler Cuci Setrika 3 hari',
                'type' => 'Kiloan',
                'price' => 7000,
                'weight' => 0.8,
                'total_price' => 5600,
                'customer_id' => 1,
            ],
            [
                'entry_date' => '2025-7-6',
                'exit_date' => '2025-7-10',
                'status' => 'Selesai',
                'order_package' => 'Reguler Cuci Lipat 3 hari',
                'type' => 'Kiloan',
                'price' => 6000,
                'weight' => 2.8,
                'total_price' => 16800,
                'customer_id' => 5,
            ],
            [
                'entry_date' => '2025-7-6',
                'exit_date' => '2025-7-10',
                'status' => 'Selesai',
                'order_package' => 'Reguler Cuci Setrika 3 hari',
                'type' => 'Kiloan',
                'price' => 7000,
                'weight' => 0.9,
                'total_price' => 6300,
                'customer_id' => 5,
            ],
            [
                'entry_date' => '2025-7-7',
                'exit_date' => null,
                'status' => 'Selesai Diproses',
                'order_package' => 'Reguler Cuci Setrika 3 hari',
                'type' => 'Kiloan',
                'price' => 7000,
                'weight' => 9.9,
                'total_price' => 69300,
                'customer_id' => 2,
            ],
            [
                'entry_date' => '2025-7-7',
                'exit_date' => '2025-7-10',
                'status' => 'Selesai',
                'order_package' => 'Reguler Cuci Setrika 3 hari',
                'type' => 'Kiloan',
                'price' => 7000,
                'weight' => 6,
                'total_price' => 42000,
                'customer_id' => 17,
            ],
            [
                'entry_date' => '2025-7-7',
                'exit_date' => '2025-7-10',
                'status' => 'Selesai',
                'order_package' => 'Selimut',
                'type' => 'Lembaran',
                'price' => 10000,
                'quantity' => 1,
                'total_price' => 10000,
                'customer_id' => 17,
            ],
            [
                'entry_date' => '2025-7-7',
                'exit_date' => null,
                'status' => 'Selesai Diproses',
                'order_package' => 'Reguler Cuci Setrika 3 hari',
                'type' => 'Kiloan',
                'price' => 7000,
                'weight' => 3.3,
                'total_price' => 23100,
                'customer_id' => 13,
            ],
            [
                'entry_date' => '2025-7-7',
                'exit_date' => '2025-7-8',
                'status' => 'Selesai',
                'order_package' => 'Reguler Cuci Lipat 3 hari',
                'type' => 'Kiloan',
                'price' => 6000,
                'weight' => 4.6,
                'total_price' => 27600,
                'customer_id' => 11,
            ],
            [
                'entry_date' => '2025-7-8',
                'exit_date' => null,
                'status' => 'Selesai Diproses',
                'order_package' => 'Ambal',
                'type' => 'Lembaran',
                'price' => 30000,
                'quantity' => 1,
                'total_price' => 30000,
                'customer_id' => 23,
            ],
            [
                'entry_date' => '2025-7-9',
                'exit_date' => '2025-7-12',
                'status' => 'Selesai',
                'order_package' => 'Reguler Cuci Setrika 3 hari',
                'type' => 'Kiloan',
                'price' => 7000,
                'weight' => 8.3,
                'total_price' => 58100,
                'customer_id' => 9,
            ],
            [
                'entry_date' => '2025-7-9',
                'exit_date' => '2025-7-12',
                'status' => 'Selesai',
                'order_package' => 'Selimut',
                'type' => 'Lembaran',
                'price' => 10000,
                'quantity' => 1,
                'total_price' => 10000,
                'customer_id' => 9,
            ],
            [
                'entry_date' => '2025-7-9',
                'exit_date' => null,
                'status' => 'Selesai Diproses',
                'order_package' => 'Reguler Cuci Setrika 3 hari',
                'type' => 'Kiloan',
                'price' => 7000,
                'weight' => 7,
                'total_price' => 49000,
                'customer_id' => 12,
            ],
            [
                'entry_date' => '2025-7-9',
                'exit_date' => null,
                'status' => 'Selesai Diproses',
                'order_package' => 'Reguler Cuci Setrika Lainnya',
                'type' => 'Kiloan',
                'price' => 10000,
                'weight' => 3.1,
                'total_price' => 31000,
                'customer_id' => 12,
            ],
            [
                'entry_date' => '2025-7-9',
                'exit_date' => null,
                'status' => 'Selesai Diproses',
                'order_package' => 'Bedcover Besar',
                'type' => 'Lembaran',
                'price' => 35000,
                'quantity' => 1,
                'total_price' => 35000,
                'customer_id' => 12,
            ],
            [
                'entry_date' => '2025-7-9',
                'exit_date' => null,
                'status' => 'Selesai Diproses',
                'order_package' => 'Reguler Cuci Setrika 3 hari',
                'type' => 'Kiloan',
                'price' => 7000,
                'weight' => 2.1,
                'total_price' => 14700,
                'customer_id' => 26,
            ],
            [
                'entry_date' => '2025-7-9',
                'exit_date' => null,
                'status' => 'Selesai Diproses',
                'order_package' => 'Reguler Cuci Setrika 3 hari',
                'type' => 'Kiloan',
                'price' => 7000,
                'weight' => 3.5,
                'total_price' => 24500,
                'customer_id' => 11,
            ],
            [
                'entry_date' => '2025-7-9',
                'exit_date' => null,
                'status' => 'Selesai Diproses',
                'order_package' => 'Reguler Cuci Setrika 3 hari',
                'type' => 'Kiloan',
                'price' => 7000,
                'weight' => 9.5,
                'total_price' => 66500,
                'customer_id' => 2,
            ],
            [
                'entry_date' => '2025-7-9',
                'exit_date' => null,
                'status' => 'Selesai Diproses',
                'order_package' => 'Seprai',
                'type' => 'Kiloan',
                'price' => 10000,
                'quantity' => 1,
                'total_price' => 10000,
                'customer_id' => 2,
            ],
            [
                'entry_date' => '2025-7-10',
                'exit_date' => '2025-7-13',
                'status' => 'Selesai',
                'order_package' => 'Ambal',
                'type' => 'Lembaran',
                'price' => 30000,
                'quantity' => 1,
                'total_price' => 30000,
                'customer_id' => 27,
            ],
            [
                'entry_date' => '2025-7-10',
                'exit_date' => '2025-7-13',
                'status' => 'Selesai',
                'order_package' => 'Ambal Besar',
                'type' => 'Lembaran',
                'price' => 50000,
                'quantity' => 1,
                'total_price' => 50000,
                'customer_id' => 27,
            ],
            [
                'entry_date' => '2025-7-10',
                'exit_date' => '2025-7-13',
                'status' => 'Selesai',
                'order_package' => 'Karpet Tebal',
                'type' => 'Lembaran',
                'price' => 15000,
                'quantity' => 1,
                'total_price' => 15000,
                'customer_id' => 27,
            ],
            [
                'entry_date' => '2025-7-10',
                'exit_date' => '2025-7-13',
                'status' => 'Selesai',
                'order_package' => 'Reguler Cuci Setrika 3 hari',
                'type' => 'Kiloan',
                'price' => 7000,
                'weight' => 6.9,
                'total_price' => 48300,
                'customer_id' => 6,
            ],
            [
                'entry_date' => '2025-7-10',
                'exit_date' => null,
                'status' => 'Selesai Diproses',
                'order_package' => 'Reguler Cuci Setrika 3 hari',
                'type' => 'Kiloan',
                'price' => 7000,
                'weight' => 1,
                'total_price' => 7000,
                'customer_id' => 4,
            ],
            [
                'entry_date' => '2025-7-10',
                'exit_date' => '2025-7-13',
                'status' => 'Selesai',
                'order_package' => 'Reguler Cuci Lipat 3 hari',
                'type' => 'Kiloan',
                'price' => 6000,
                'weight' => 3.7,
                'total_price' => 22200,
                'customer_id' => 5,
            ],
            [
                'entry_date' => '2025-7-10',
                'exit_date' => '2025-7-13',
                'status' => 'Selesai',
                'order_package' => 'Reguler Cuci Setrika 3 hari',
                'type' => 'Kiloan',
                'price' => 7000,
                'weight' => 1.2,
                'total_price' => 8400,
                'customer_id' => 5,
            ],
            [
                'entry_date' => '2025-7-11',
                'exit_date' => null,
                'status' => 'Baru',
                'order_package' => 'Reguler Cuci Setrika 3 hari',
                'type' => 'Kiloan',
                'price' => 7000,
                'weight' => null,
                'total_price' => null,
                'customer_id' => 3,
            ],
            [
                'entry_date' => '2025-7-11',
                'exit_date' => '2025-7-13',
                'status' => 'Selesai',
                'order_package' => 'Reguler Cuci Setrika 2 hari',
                'type' => 'Kiloan',
                'price' => 8000,
                'weight' => 3.5,
                'total_price' => 28000,
                'customer_id' => 15,
            ],
            [
                'entry_date' => '2025-7-12',
                'exit_date' => null,
                'status' => 'Selesai Diproses',
                'order_package' => 'Reguler Cuci Lipat 3 hari',
                'type' => 'Kiloan',
                'price' => 6000,
                'weight' => 5.9,
                'total_price' => 35400,
                'customer_id' => 20,
            ],
            [
                'entry_date' => '2025-7-12',
                'exit_date' => null,
                'status' => 'Selesai Diproses',
                'order_package' => 'Reguler Cuci Setrika 3 hari',
                'type' => 'Kiloan',
                'price' => 7000,
                'weight' => 5.5,
                'total_price' => 38500,
                'customer_id' => 2,
            ],
            [
                'entry_date' => '2025-7-12',
                'exit_date' => null,
                'status' => 'Baru',
                'order_package' => 'Reguler Cuci Setrika 3 hari',
                'type' => 'Kiloan',
                'price' => 7000,
                'weight' => null,
                'total_price' => null,
                'customer_id' => 9,
            ],
            [
                'entry_date' => '2025-7-13',
                'exit_date' => null,
                'status' => 'Baru',
                'order_package' => 'Reguler Cuci Setrika 3 hari',
                'type' => 'Kiloan',
                'price' => 7000,
                'weight' => null,
                'total_price' => null,
                'customer_id' => 6,
            ],
            [
                'entry_date' => '2025-7-13',
                'exit_date' => null,
                'status' => 'Baru',
                'order_package' => 'Reguler Cuci Setrika 3 hari',
                'type' => 'Kiloan',
                'price' => 7000,
                'weight' => null,
                'total_price' => null,
                'customer_id' => 4,
            ],
            [
                'entry_date' => '2025-7-14',
                'exit_date' => null,
                'status' => 'Baru',
                'order_package' => 'Reguler Cuci Setrika 3 hari',
                'type' => 'Kiloan',
                'price' => 7000,
                'weight' => null,
                'total_price' => null,
                'customer_id' => 17,
            ],
        ];

        foreach ($orders as $o) {
            Order::create($o);
        }
    }
}
