<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Spatie\Permission\Models\Permission;

class PermissionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $permissions = [
            ['name' => 'view_role', 'guard_name' => 'web'],
            ['name' => 'view_any_role', 'guard_name' => 'web'],
            ['name' => 'create_role', 'guard_name' => 'web'],
            ['name' => 'update_role', 'guard_name' => 'web'],
            ['name' => 'delete_role', 'guard_name' => 'web'],
            ['name' => 'delete_any_role', 'guard_name' => 'web'],
            ['name' => 'view_customer', 'guard_name' => 'web'],
            ['name' => 'view_any_customer', 'guard_name' => 'web'],
            ['name' => 'create_customer', 'guard_name' => 'web'],
            ['name' => 'update_customer', 'guard_name' => 'web'],
            ['name' => 'restore_customer', 'guard_name' => 'web'],
            ['name' => 'restore_any_customer', 'guard_name' => 'web'],
            ['name' => 'replicate_customer', 'guard_name' => 'web'],
            ['name' => 'reorder_customer', 'guard_name' => 'web'],
            ['name' => 'delete_customer', 'guard_name' => 'web'],
            ['name' => 'delete_any_customer', 'guard_name' => 'web'],
            ['name' => 'force_delete_customer', 'guard_name' => 'web'],
            ['name' => 'force_delete_any_customer', 'guard_name' => 'web'],
            ['name' => 'view_discount', 'guard_name' => 'web'],
            ['name' => 'view_any_discount', 'guard_name' => 'web'],
            ['name' => 'create_discount', 'guard_name' => 'web'],
            ['name' => 'update_discount', 'guard_name' => 'web'],
            ['name' => 'restore_discount', 'guard_name' => 'web'],
            ['name' => 'restore_any_discount', 'guard_name' => 'web'],
            ['name' => 'replicate_discount', 'guard_name' => 'web'],
            ['name' => 'reorder_discount', 'guard_name' => 'web'],
            ['name' => 'delete_discount', 'guard_name' => 'web'],
            ['name' => 'delete_any_discount', 'guard_name' => 'web'],
            ['name' => 'force_delete_discount', 'guard_name' => 'web'],
            ['name' => 'force_delete_any_discount', 'guard_name' => 'web'],
            ['name' => 'view_expense', 'guard_name' => 'web'],
            ['name' => 'view_any_expense', 'guard_name' => 'web'],
            ['name' => 'create_expense', 'guard_name' => 'web'],
            ['name' => 'update_expense', 'guard_name' => 'web'],
            ['name' => 'restore_expense', 'guard_name' => 'web'],
            ['name' => 'restore_any_expense', 'guard_name' => 'web'],
            ['name' => 'replicate_expense', 'guard_name' => 'web'],
            ['name' => 'reorder_expense', 'guard_name' => 'web'],
            ['name' => 'delete_expense', 'guard_name' => 'web'],
            ['name' => 'delete_any_expense', 'guard_name' => 'web'],
            ['name' => 'force_delete_expense', 'guard_name' => 'web'],
            ['name' => 'force_delete_any_expense', 'guard_name' => 'web'],
            ['name' => 'view_order', 'guard_name' => 'web'],
            ['name' => 'view_any_order', 'guard_name' => 'web'],
            ['name' => 'create_order', 'guard_name' => 'web'],
            ['name' => 'update_order', 'guard_name' => 'web'],
            ['name' => 'restore_order', 'guard_name' => 'web'],
            ['name' => 'restore_any_order', 'guard_name' => 'web'],
            ['name' => 'replicate_order', 'guard_name' => 'web'],
            ['name' => 'reorder_order', 'guard_name' => 'web'],
            ['name' => 'delete_order', 'guard_name' => 'web'],
            ['name' => 'delete_any_order', 'guard_name' => 'web'],
            ['name' => 'force_delete_order', 'guard_name' => 'web'],
            ['name' => 'force_delete_any_order', 'guard_name' => 'web'],
            ['name' => 'view_order::package', 'guard_name' => 'web'],
            ['name' => 'view_any_order::package', 'guard_name' => 'web'],
            ['name' => 'create_order::package', 'guard_name' => 'web'],
            ['name' => 'update_order::package', 'guard_name' => 'web'],
            ['name' => 'restore_order::package', 'guard_name' => 'web'],
            ['name' => 'restore_any_order::package', 'guard_name' => 'web'],
            ['name' => 'replicate_order::package', 'guard_name' => 'web'],
            ['name' => 'reorder_order::package', 'guard_name' => 'web'],
            ['name' => 'delete_order::package', 'guard_name' => 'web'],
            ['name' => 'delete_any_order::package', 'guard_name' => 'web'],
            ['name' => 'force_delete_order::package', 'guard_name' => 'web'],
            ['name' => 'force_delete_any_order::package', 'guard_name' => 'web'],
            ['name' => 'page_Localization', 'guard_name' => 'web'],
            ['name' => 'page_LoginPageImage', 'guard_name' => 'web'],
            ['name' => 'widget_StatsOverview', 'guard_name' => 'web'],
            ['name' => 'widget_StatsOverview2', 'guard_name' => 'web'],
            ['name' => 'widget_FinancialChart', 'guard_name' => 'web'],
            ['name' => 'page_EditProfilePage', 'guard_name' => 'web'],
            ['name' => 'page_EditProfile', 'guard_name' => 'web'],
            ['name' => 'page_AddressAndWhatsapp', 'guard_name' => 'web'],
            ['name' => 'view_customer::order', 'guard_name' => 'web'],
            ['name' => 'view_any_customer::order', 'guard_name' => 'web'],
            ['name' => 'create_customer::order', 'guard_name' => 'web'],
            ['name' => 'update_customer::order', 'guard_name' => 'web'],
            ['name' => 'restore_customer::order', 'guard_name' => 'web'],
            ['name' => 'restore_any_customer::order', 'guard_name' => 'web'],
            ['name' => 'replicate_customer::order', 'guard_name' => 'web'],
            ['name' => 'reorder_customer::order', 'guard_name' => 'web'],
            ['name' => 'delete_customer::order', 'guard_name' => 'web'],
            ['name' => 'delete_any_customer::order', 'guard_name' => 'web'],
            ['name' => 'force_delete_customer::order', 'guard_name' => 'web'],
            ['name' => 'force_delete_any_customer::order', 'guard_name' => 'web'],
            ['name' => 'view_customer::pickup::delivery', 'guard_name' => 'web'],
            ['name' => 'view_any_customer::pickup::delivery', 'guard_name' => 'web'],
            ['name' => 'create_customer::pickup::delivery', 'guard_name' => 'web'],
            ['name' => 'update_customer::pickup::delivery', 'guard_name' => 'web'],
            ['name' => 'restore_customer::pickup::delivery', 'guard_name' => 'web'],
            ['name' => 'restore_any_customer::pickup::delivery', 'guard_name' => 'web'],
            ['name' => 'replicate_customer::pickup::delivery', 'guard_name' => 'web'],
            ['name' => 'reorder_customer::pickup::delivery', 'guard_name' => 'web'],
            ['name' => 'delete_customer::pickup::delivery', 'guard_name' => 'web'],
            ['name' => 'delete_any_customer::pickup::delivery', 'guard_name' => 'web'],
            ['name' => 'force_delete_customer::pickup::delivery', 'guard_name' => 'web'],
            ['name' => 'force_delete_any_customer::pickup::delivery', 'guard_name' => 'web'],
            ['name' => 'widget_CustomerStatsOverview', 'guard_name' => 'web'],
            ['name' => 'widget_ActiveOrdersTable', 'guard_name' => 'web'],
            ['name' => 'widget_ActivePickupDeliveriesTable', 'guard_name' => 'web'],
            ['name' => 'view_pickup::delivery', 'guard_name' => 'web'],
            ['name' => 'view_any_pickup::delivery', 'guard_name' => 'web'],
            ['name' => 'create_pickup::delivery', 'guard_name' => 'web'],
            ['name' => 'update_pickup::delivery', 'guard_name' => 'web'],
            ['name' => 'restore_pickup::delivery', 'guard_name' => 'web'],
            ['name' => 'restore_any_pickup::delivery', 'guard_name' => 'web'],
            ['name' => 'replicate_pickup::delivery', 'guard_name' => 'web'],
            ['name' => 'reorder_pickup::delivery', 'guard_name' => 'web'],
            ['name' => 'delete_pickup::delivery', 'guard_name' => 'web'],
            ['name' => 'delete_any_pickup::delivery', 'guard_name' => 'web'],
            ['name' => 'force_delete_pickup::delivery', 'guard_name' => 'web'],
            ['name' => 'force_delete_any_pickup::delivery', 'guard_name' => 'web'],
            ['name' => 'widget_ClockWidget', 'guard_name' => 'web'],
            ['name' => 'page_WhatsappNotificationSetting', 'guard_name' => 'web'],
            ['name' => 'view_whatsapp::broadcast', 'guard_name' => 'web'],
            ['name' => 'view_any_whatsapp::broadcast', 'guard_name' => 'web'],
            ['name' => 'create_whatsapp::broadcast', 'guard_name' => 'web'],
            ['name' => 'update_whatsapp::broadcast', 'guard_name' => 'web'],
            ['name' => 'restore_whatsapp::broadcast', 'guard_name' => 'web'],
            ['name' => 'restore_any_whatsapp::broadcast', 'guard_name' => 'web'],
            ['name' => 'replicate_whatsapp::broadcast', 'guard_name' => 'web'],
            ['name' => 'reorder_whatsapp::broadcast', 'guard_name' => 'web'],
            ['name' => 'delete_whatsapp::broadcast', 'guard_name' => 'web'],
            ['name' => 'delete_any_whatsapp::broadcast', 'guard_name' => 'web'],
            ['name' => 'force_delete_whatsapp::broadcast', 'guard_name' => 'web'],
            ['name' => 'force_delete_any_whatsapp::broadcast', 'guard_name' => 'web'],
        ];

        foreach ($permissions as $permission) {
            Permission::create($permission);
        }
    }
}
