<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\PickupDelivery;


class PickupDeliverySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $pickupDeliveries = [
            [
                'date' => '2025-9-1',
                'time' => '00:00:00',
                'type' => 'Jemput',
                'status' => 'Selesai',
                'customer_note' => null,
                'laundry_note' => null,
                'customer_id' => 3,
            ],
            [
                'date' => '2025-9-6',
                'time' => '00:00:00',
                'type' => 'Jemput',
                'status' => 'Selesai',
                'customer_note' => null,
                'laundry_note' => null,
                'customer_id' => 3,
            ],
            [
                'date' => '2025-9-10',
                'time' => '00:00:00',
                'type' => 'Jemput',
                'status' => 'Selesai',
                'customer_note' => null,
                'laundry_note' => null,
                'customer_id' => 3,
            ],
            [
                'date' => '2025-9-14',
                'time' => '00:00:00',
                'type' => 'Jemput',
                'status' => 'Selesai',
                'customer_note' => null,
                'laundry_note' => null,
                'customer_id' => 3,
            ],
            [
                'date' => '2025-9-18',
                'time' => '00:00:00',
                'type' => 'Antar dan Jemput',
                'status' => 'Selesai',
                'customer_note' => null,
                'laundry_note' => null,
                'customer_id' => 3,
            ],
            [
                'date' => '2025-9-22',
                'time' => '00:00:00',
                'type' => 'Jemput',
                'status' => 'Selesai',
                'customer_note' => null,
                'laundry_note' => null,
                'customer_id' => 3,
            ],
            [
                'date' => '2025-9-26',
                'time' => '00:00:00',
                'type' => 'Jemput',
                'status' => 'Selesai',
                'customer_note' => null,
                'laundry_note' => null,
                'customer_id' => 3,
            ],
            [
                'date' => '2025-10-1',
                'time' => '00:00:00',
                'type' => 'Antar dan Jemput',
                'status' => 'Selesai',
                'customer_note' => null,
                'laundry_note' => null,
                'customer_id' => 3,
            ],
            [
                'date' => '2025-10-1',
                'time' => '00:00:00',
                'type' => 'Antar',
                'status' => 'Selesai',
                'customer_note' => null,
                'laundry_note' => null,
                'customer_id' => 3,
            ],
            [
                'date' => '2025-10-6',
                'time' => '00:00:00',
                'type' => 'Jemput',
                'status' => 'Selesai',
                'customer_note' => null,
                'laundry_note' => null,
                'customer_id' => 3,
            ],
            [
                'date' => '2025-10-11',
                'time' => '00:00:00',
                'type' => 'Jemput',
                'status' => 'Selesai',
                'customer_note' => null,
                'laundry_note' => null,
                'customer_id' => 3,
            ],

            [
                'date' => '2025-10-6',
                'time' => '00:00:00',
                'type' => 'Antar dan Jemput',
                'status' => 'Selesai',
                'customer_note' => null,
                'laundry_note' => null,
                'customer_id' => 5,
            ],
            [
                'date' => '2025-10-10',
                'time' => '00:00:00',
                'type' => 'Jemput',
                'status' => 'Selesai',
                'customer_note' => null,
                'laundry_note' => null,
                'customer_id' => 5,
            ],
            [
                'date' => '2025-9-12',
                'time' => '00:00:00',
                'type' => 'Antar dan Jemput',
                'status' => 'Selesai',
                'customer_note' => null,
                'laundry_note' => null,
                'customer_id' => 4,
            ],
            [
                'date' => '2025-9-22',
                'time' => '00:00:00',
                'type' => 'Jemput',
                'status' => 'Selesai',
                'customer_note' => null,
                'laundry_note' => null,
                'customer_id' => 4,
            ],
            [
                'date' => '2025-9-29',
                'time' => '00:00:00',
                'type' => 'Jemput',
                'status' => 'Selesai',
                'customer_note' => null,
                'laundry_note' => null,
                'customer_id' => 4,
            ],
            [
                'date' => '2025-10-3',
                'time' => '00:00:00',
                'type' => 'Jemput',
                'status' => 'Selesai',
                'customer_note' => null,
                'laundry_note' => null,
                'customer_id' => 4,
            ],
            [
                'date' => '2025-10-5',
                'time' => '00:00:00',
                'type' => 'Antar dan Jemput',
                'status' => 'Selesai',
                'customer_note' => null,
                'laundry_note' => null,
                'customer_id' => 4,
            ],
            [
                'date' => '2025-9-15',
                'time' => '00:00:00',
                'type' => 'Antar dan Jemput',
                'status' => 'Selesai',
                'customer_note' => null,
                'laundry_note' => null,
                'customer_id' => 12,
            ],
            [
                'date' => '2025-9-20',
                'time' => '00:00:00',
                'type' => 'Antar dan Jemput',
                'status' => 'Selesai',
                'customer_note' => null,
                'laundry_note' => null,
                'customer_id' => 12,
            ],
            [
                'date' => '2025-9-26',
                'time' => '00:00:00',
                'type' => 'Antar dan Jemput',
                'status' => 'Selesai',
                'customer_note' => null,
                'laundry_note' => null,
                'customer_id' => 12,
            ],
            [
                'date' => '2025-10-1',
                'time' => '00:00:00',
                'type' => 'Antar dan Jemput',
                'status' => 'Selesai',
                'customer_note' => null,
                'laundry_note' => null,
                'customer_id' => 12,
            ],
            [
                'date' => '2025-10-5',
                'time' => '00:00:00',
                'type' => 'Antar dan Jemput',
                'status' => 'Selesai',
                'customer_note' => null,
                'laundry_note' => null,
                'customer_id' => 12,
            ],
            [
                'date' => '2025-10-9',
                'time' => '00:00:00',
                'type' => 'Antar dan Jemput',
                'status' => 'Selesai',
                'customer_note' => null,
                'laundry_note' => null,
                'customer_id' => 12,
            ],
            [
                'date' => '2025-9-8',
                'time' => '00:00:00',
                'type' => 'Antar dan Jemput',
                'status' => 'Selesai',
                'customer_note' => null,
                'laundry_note' => null,
                'customer_id' => 17,
            ],
            [
                'date' => '2025-9-16',
                'time' => '00:00:00',
                'type' => 'Antar',
                'status' => 'Selesai',
                'customer_note' => null,
                'laundry_note' => null,
                'customer_id' => 17,
            ],
            [
                'date' => '2025-9-20',
                'time' => '00:00:00',
                'type' => 'Jemput',
                'status' => 'Selesai',
                'customer_note' => null,
                'laundry_note' => null,
                'customer_id' => 17,
            ],
            [
                'date' => '2025-9-24',
                'time' => '00:00:00',
                'type' => 'Antar dan Jemput',
                'status' => 'Selesai',
                'customer_note' => null,
                'laundry_note' => null,
                'customer_id' => 17,
            ],
            [
                'date' => '2025-9-29',
                'time' => '00:00:00',
                'type' => 'Antar dan Jemput',
                'status' => 'Selesai',
                'customer_note' => null,
                'laundry_note' => null,
                'customer_id' => 17,
            ],
            [
                'date' => '2025-10-7',
                'time' => '00:00:00',
                'type' => 'Jemput',
                'status' => 'Selesai',
                'customer_note' => null,
                'laundry_note' => null,
                'customer_id' => 17,
            ],
        ];

        foreach ($pickupDeliveries as $p) {
            PickupDelivery::create($p);
        }
    }
}
