<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\PickupDelivery;


class PickupDeliverySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $pickupDeliveries = [
            [
                'date' => '2025-7-1',
                'time' => '00:00:00',
                'type' => 'Jemput',
                'status' => 'Selesai',
                'customer_note' => null,
                'laundry_note' => null,
                'customer_id' => 3,
            ],
            [
                'date' => '2025-7-6',
                'time' => '00:00:00',
                'type' => 'Jemput',
                'status' => 'Selesai',
                'customer_note' => null,
                'laundry_note' => null,
                'customer_id' => 3,
            ],
            [
                'date' => '2025-7-10',
                'time' => '00:00:00',
                'type' => 'Jemput',
                'status' => 'Selesai',
                'customer_note' => null,
                'laundry_note' => null,
                'customer_id' => 3,
            ],
            [
                'date' => '2025-7-14',
                'time' => '00:00:00',
                'type' => 'Jemput',
                'status' => 'Selesai',
                'customer_note' => null,
                'laundry_note' => null,
                'customer_id' => 3,
            ],
            [
                'date' => '2025-7-18',
                'time' => '00:00:00',
                'type' => 'Antar dan Jemput',
                'status' => 'Selesai',
                'customer_note' => null,
                'laundry_note' => null,
                'customer_id' => 3,
            ],
            [
                'date' => '2025-7-22',
                'time' => '00:00:00',
                'type' => 'Jemput',
                'status' => 'Selesai',
                'customer_note' => null,
                'laundry_note' => null,
                'customer_id' => 3,
            ],
            [
                'date' => '2025-7-26',
                'time' => '00:00:00',
                'type' => 'Jemput',
                'status' => 'Selesai',
                'customer_note' => null,
                'laundry_note' => null,
                'customer_id' => 3,
            ],
            [
                'date' => '2025-8-1',
                'time' => '00:00:00',
                'type' => 'Antar dan Jemput',
                'status' => 'Selesai',
                'customer_note' => null,
                'laundry_note' => null,
                'customer_id' => 3,
            ],
            [
                'date' => '2025-8-1',
                'time' => '00:00:00',
                'type' => 'Antar',
                'status' => 'Selesai',
                'customer_note' => null,
                'laundry_note' => null,
                'customer_id' => 3,
            ],
            [
                'date' => '2025-8-6',
                'time' => '00:00:00',
                'type' => 'Jemput',
                'status' => 'Selesai',
                'customer_note' => null,
                'laundry_note' => null,
                'customer_id' => 3,
            ],
            [
                'date' => '2025-8-11',
                'time' => '00:00:00',
                'type' => 'Jemput',
                'status' => 'Selesai',
                'customer_note' => null,
                'laundry_note' => null,
                'customer_id' => 3,
            ],

            [
                'date' => '2025-8-6',
                'time' => '00:00:00',
                'type' => 'Antar dan Jemput',
                'status' => 'Selesai',
                'customer_note' => null,
                'laundry_note' => null,
                'customer_id' => 5,
            ],
            [
                'date' => '2025-8-10',
                'time' => '00:00:00',
                'type' => 'Jemput',
                'status' => 'Selesai',
                'customer_note' => null,
                'laundry_note' => null,
                'customer_id' => 5,
            ],
            [
                'date' => '2025-7-12',
                'time' => '00:00:00',
                'type' => 'Antar dan Jemput',
                'status' => 'Selesai',
                'customer_note' => null,
                'laundry_note' => null,
                'customer_id' => 4,
            ],
            [
                'date' => '2025-7-22',
                'time' => '00:00:00',
                'type' => 'Jemput',
                'status' => 'Selesai',
                'customer_note' => null,
                'laundry_note' => null,
                'customer_id' => 4,
            ],
            [
                'date' => '2025-7-29',
                'time' => '00:00:00',
                'type' => 'Jemput',
                'status' => 'Selesai',
                'customer_note' => null,
                'laundry_note' => null,
                'customer_id' => 4,
            ],
            [
                'date' => '2025-8-3',
                'time' => '00:00:00',
                'type' => 'Jemput',
                'status' => 'Selesai',
                'customer_note' => null,
                'laundry_note' => null,
                'customer_id' => 4,
            ],
            [
                'date' => '2025-8-5',
                'time' => '00:00:00',
                'type' => 'Antar dan Jemput',
                'status' => 'Selesai',
                'customer_note' => null,
                'laundry_note' => null,
                'customer_id' => 4,
            ],
            [
                'date' => '2025-7-15',
                'time' => '00:00:00',
                'type' => 'Antar dan Jemput',
                'status' => 'Selesai',
                'customer_note' => null,
                'laundry_note' => null,
                'customer_id' => 12,
            ],
            [
                'date' => '2025-7-20',
                'time' => '00:00:00',
                'type' => 'Antar dan Jemput',
                'status' => 'Selesai',
                'customer_note' => null,
                'laundry_note' => null,
                'customer_id' => 12,
            ],
            [
                'date' => '2025-7-26',
                'time' => '00:00:00',
                'type' => 'Antar dan Jemput',
                'status' => 'Selesai',
                'customer_note' => null,
                'laundry_note' => null,
                'customer_id' => 12,
            ],
            [
                'date' => '2025-8-1',
                'time' => '00:00:00',
                'type' => 'Antar dan Jemput',
                'status' => 'Selesai',
                'customer_note' => null,
                'laundry_note' => null,
                'customer_id' => 12,
            ],
            [
                'date' => '2025-8-5',
                'time' => '00:00:00',
                'type' => 'Antar dan Jemput',
                'status' => 'Selesai',
                'customer_note' => null,
                'laundry_note' => null,
                'customer_id' => 12,
            ],
            [
                'date' => '2025-8-9',
                'time' => '00:00:00',
                'type' => 'Antar dan Jemput',
                'status' => 'Selesai',
                'customer_note' => null,
                'laundry_note' => null,
                'customer_id' => 12,
            ],
            [
                'date' => '2025-7-8',
                'time' => '00:00:00',
                'type' => 'Antar dan Jemput',
                'status' => 'Selesai',
                'customer_note' => null,
                'laundry_note' => null,
                'customer_id' => 17,
            ],
            [
                'date' => '2025-7-16',
                'time' => '00:00:00',
                'type' => 'Antar',
                'status' => 'Selesai',
                'customer_note' => null,
                'laundry_note' => null,
                'customer_id' => 17,
            ],
            [
                'date' => '2025-7-20',
                'time' => '00:00:00',
                'type' => 'Jemput',
                'status' => 'Selesai',
                'customer_note' => null,
                'laundry_note' => null,
                'customer_id' => 17,
            ],
            [
                'date' => '2025-7-24',
                'time' => '00:00:00',
                'type' => 'Antar dan Jemput',
                'status' => 'Selesai',
                'customer_note' => null,
                'laundry_note' => null,
                'customer_id' => 17,
            ],
            [
                'date' => '2025-7-29',
                'time' => '00:00:00',
                'type' => 'Antar dan Jemput',
                'status' => 'Selesai',
                'customer_note' => null,
                'laundry_note' => null,
                'customer_id' => 17,
            ],
            [
                'date' => '2025-8-7',
                'time' => '00:00:00',
                'type' => 'Jemput',
                'status' => 'Selesai',
                'customer_note' => null,
                'laundry_note' => null,
                'customer_id' => 17,
            ],
        ];

        foreach ($pickupDeliveries as $p) {
            PickupDelivery::create($p);
        }
    }
}
